### ISSUE TITLE
Re-add --rva option

### ISSUE THREAD

**Issue by moshekaplan** [0vercl0k/rp#17]
Previous versions of this tool allowed specifying an RVA. Would it be possible to re-add that command?

**Comment by 0vercl0k** [comment]
The RVA option has never been there for the released binaries as far as I
know - I added it only in the next branch (which is somewhat broken at the
moment). It shouldn't be hard to back-port it though, here is the original
commit:
https://github.com/0vercl0k/rp/commit/2b5d8d9e32c9a948d7d3a6f76c6cee104bd6a8cf
.

Note that, the original intent of RVA was to only display RVA if you enable
the switch, but I've repurposed the option so that you can provide your own
VA instead (it can also be 0 if you want only RVAs). I should even rename
the option to VA which would be way more accurate & less confusing.

Cheers

2016-02-03 5:42 GMT-08:00 Moshe Kaplan <notifications@github.com>:

**Comment by 0vercl0k** [comment]
I'm closing this - feel free to re-open to discuss this.

Cheers
