### ISSUE TITLE
Specify architecture manually

### ISSUE THREAD

**Issue by CTurt** [0vercl0k/rp#9]
Some binaries fail to load with "Cannot determine the executable format used".

We should be able to specify manually the correct architecture for cases when it is detected incorrectly, or fails to detect at all.

**Comment by 0vercl0k** [comment]
A workaround to this would be dump directly dump the code you are
interested in & feed it with --raw=archyouwant.
The issue here is not about architecture though but the executable format
used -- the function supposed to select the correct one is dumb:
https://github.com/0vercl0k/rp/blob/master/src/executable_format.cpp#L33.

If it answers your questions, I would appreciate if you could close the
issue please :-).
Cheers,
0vercl0k

2015-06-18 11:44 GMT-07:00 CTurt <notifications@github.com>:

**Comment by CTurt** [comment]
Thanks very much; it's working perfectly now.

**Comment by 0vercl0k** [comment]
Great!

2015-06-20 3:41 GMT-07:00 CTurt <notifications@github.com>:
